# Location: Gemfile
# Creacion de gemfile.lock: bundle install

source "http://rubygems.org"

# Add dependencies to develop your gem here.
# Include everything needed to run rake, tests, features, etc.
group :development do
  gem 'bundler'
  gem 'rake'
  gem 'rspec'
  gem 'capybara'
  gem 'selenium-webdriver'

  gem "cucumber"
	gem "test-unit" # Actualizacion
	gem "mechanize"
	gem "capybara-mechanize"
end
